'Air' = {id = 0}
'Stone' = {id = 1, data = 0}
'Granite' = {id = 1, data = 1}
'Polished Granite' = {id = 1, data = 2}
'Diorite' = {id = 1, data = 3}
'Polished Diorite' = {id = 1, data = 4}
'Andesite' = {id = 1, data = 5}
'Polished Andesite' = {id = 1, data = 6}
'Grass' = {id = 2}
'Dirt' = {id = 3, data = 0}
'Coarse Dirt' = {id = 3, data = 1}
'Podzol' = {id = 3, data = 2}
'Cobblestone' = {id = 4}
'Oak Wood Plank' = {id = 5}
'Bedrock' = {id = 7}
'Sand' = {id = 12, data = 0}
'Red Sand' = {id = 12, data = 1}
'Still Water' = {id = 9}
# TODO complete this